version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
    driver: bridge
